apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kaiwalyakoparkar/gitops-ci-cd
    targetRevision: HEAD
    path: kubernetes/
  destination: 
    server: https://kubernetes.default.svc
    namespace: cicd-pipeline
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true