---
name: build and push docker image
on:
  push

jobs:
  release-docker:
    name: Release docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kaiwalyakoparkar/busybox
          tag_with_ref: true
          add_git_labels: true
          tag_with_sha: true
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: /Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
          push: true     

      - name: Get git sha short
        id: vars
        run: echo "name=sha_short::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Generate deploy manifest from Jinja template
        uses: cuchi/jinja2-action@v1.2.0
        with: 
          template: template/deploy.j2
          output_file: kubernetes/deploy.yaml
          strict: true
          variables: |
            image_deploy_tag=sha-${{ steps.vars.outputs.sha_short }}
            
      - name: Commit deploy manifest on local repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -s -m "[skip ci] Generate deployment manifests" 
          
      - name: Push deploy manifests to local repo
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.AUTO_COMMIT_TOKEN }}